[tools]
fzf = "latest"
gh = "latest"
go = "latest"
java = "latest"
lazygit = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
peco = "latest"
pkl = "latest"
rg = "latest"
rust = "latest"
starship = "latest"
task = "latest"
tmux = "latest"
typos = "latest"
zellij = "latest"
hk = "latest"
