[tools]
bun = "latest"
deno = "latest"
direnv = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
go = "latest"
java = "latest"
lazygit = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
peco = "latest"
pipx = "latest"
rg = "latest"
rust = "latest"
starship = "latest"
task = "latest"
terraform = "latest"
tfenv = "latest"
tmux = "latest"
typos = "latest"
zellij = "latest"

[settings]
idiomatic_version_file_enable_tools = ["terraform"]
