[tools]
deno = "latest"
direnv = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
java = "latest"
lazygit = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
peco = "latest"
pipx = "latest"
rg = "latest"
rust = "latest"
starship = "latest"
task = "latest"
terraform = "latest"
tmux = "latest"
typos = "latest"
zellij = "latest"
