git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showIcons: true
  language: 'en'
refresher:
  refreshInterval: 3
customCommands:
  - key: 'u'
    context: 'files'
    description: 'stash include untracked'
    command: 'git stash save --include-untracked "{{index .PromptResponses 0}}" '
    prompts:
      - type: 'input'
        title: 'Stash Message'
        initialValue: 'WIP'

