command_timeout = 500

[git_status]
scan_timeout = 300

[custom.os_version]
command = "uname"
format = ' [$symbol($output)]($style)'

[os.symbols]
Macos = "  " # nf-fa-apple
Ubuntu = "  " # nf-linux-ubuntu
Debian = "  " # nf-linux-debian

[golang]
format = '(via [$symbol($version )]($style))'

[nodejs]
format = '(via [$symbol($version )]($style))'

[python]
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'

[rust]
format = '(via [$symbol($version )]($style))'

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 10
style = 'bold red'

[git_metrics]
disabled = true
