command_timeout = 1000

[golang]
format = '(via [$symbol($version )]($style))'

[nodejs]
format = '(via [$symbol($version )]($style))'

[python]
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'

[rust]
format = '(via [$symbol($version )]($style))'

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 10
style = 'bold red'

[git_metrics]
disabled = true
