name: macbook

on:
  pull_request:
    branches: [ main ]
jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run brew bundle macbook
      run: |
        sh init.sh
        brew install neovim \
          tmux vim git

    - name: zsh
      run: |
        sh zsh_link.sh

    - name: vim 
      run: |
        sh vim_link.sh

    - name: tmux
      run: |
        sh tmuxs.sh

    - name: wezterm
      run: |
        sh wezterm.sh

